[package]
name = "quranize-wasm"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
quranize = { path = "../quranize" }
wasm-bindgen = "0.2"
serde = "1.0"
serde-wasm-bindgen = "0.6"

[dev-dependencies]
pretty_assertions = "1"
