name: Continuous Integration

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo test
      - run: cargo clippy
