name: Cloudflare Pages Deployment

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

concurrency:
  group: deployment-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v6
      - run: rustup target add wasm32-unknown-unknown
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: extractions/setup-just@v2
      - run: just prepare-deployment
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy app/web/dist --project-name=quranize
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
